In [15]:
# Looking into the data to see what we have to work with

import nfl_data_py as nfl
import pandas as pd

years_experiment = list(range(2015, 2025)) 
years = list(range(2015,2026))
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [16]:
print([f for f in dir(nfl) if f.startswith('import_')])

['import_combine_data', 'import_contracts', 'import_depth_charts', 'import_draft_picks', 'import_draft_values', 'import_ftn_data', 'import_ids', 'import_injuries', 'import_ngs_data', 'import_officials', 'import_pbp_data', 'import_players', 'import_qbr', 'import_sc_lines', 'import_schedules', 'import_seasonal_data', 'import_seasonal_pfr', 'import_seasonal_rosters', 'import_snap_counts', 'import_team_desc', 'import_weekly_data', 'import_weekly_pfr', 'import_weekly_rosters', 'import_win_totals']

In [17]:
teams = nfl.import_team_desc()
print(teams.shape)
teams.info()
teams.head()

(36, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   team_abbr             36 non-null     object
 1   team_name             36 non-null     object
 2   team_id               36 non-null     int64
 3   team_nick             36 non-null     object
 4   team_conf             36 non-null     object
 5   team_division         36 non-null     object
 6   team_color            36 non-null     object
 7   team_color2           36 non-null     object
 8   team_color3           34 non-null     object
 9   team_color4           34 non-null     object
 10  team_logo_wikipedia   36 non-null     object
 11  team_logo_espn        36 non-null     object
 12  team_wordmark         36 non-null     object
 13  team_conference_logo  36 non-null     object
 14  team_league_logo      36 non-null     object
 15  team_logo_squared     36 non-null     object
dtypes: int64(1), object(15)
memory usage: 4.6+ KB

,team_abbr,team_name,team_id,team_nick,team_conf,team_division,team_color,team_color2,team_color3,team_color4,team_logo_wikipedia,team_logo_espn,team_wordmark,team_conference_logo,team_league_logo,team_logo_squared
0,ARI,Arizona Cardinals,3800,Cardinals,NFC,NFC West,#97233F,#000000,#ffb612,#a5acaf,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ari.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
1,ATL,Atlanta Falcons,200,Falcons,NFC,NFC South,#A71930,#000000,#a5acaf,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/atl.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
2,BAL,Baltimore Ravens,325,Ravens,AFC,AFC North,#241773,#9E7C0C,#9e7c0c,#c60c30,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/bal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
3,BUF,Buffalo Bills,610,Bills,AFC,AFC East,#00338D,#C60C30,#0c2e82,#d50a0a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/buf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
4,CAR,Carolina Panthers,750,Panthers,NFC,NFC South,#0085CA,#000000,#bfc0bf,#0085ca,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500-dark...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...

In [18]:
players = nfl.import_players()
print(players.shape)
players.info()
players.head(10)

(25037, 39)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25037 entries, 0 to 25036
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   gsis_id                       25037 non-null  object
 1   display_name                  25037 non-null  object
 2   common_first_name             25037 non-null  object
 3   first_name                    25037 non-null  object
 4   last_name                     25037 non-null  object
 5   short_name                    8009 non-null   object
 6   football_name                 8491 non-null   object
 7   suffix                        164 non-null    object
 8   esb_id                        25037 non-null  object
 9   nfl_id                        12099 non-null  object
 10  pfr_id                        22552 non-null  object
 11  pff_id                        11251 non-null  object
 12  otc_id                        9340 non-null   object
 13  espn_id                       16749 non-null  object
 14  smart_id                      25037 non-null  object
 15  birth_date                    24992 non-null  object
 16  position_group                25037 non-null  object
 17  position                      25037 non-null  object
 18  ngs_position_group            2851 non-null   object
 19  ngs_position                  2763 non-null   object
 20  height                        25027 non-null  float64
 21  weight                        25026 non-null  float64
 22  headshot                      24837 non-null  object
 23  college_name                  25037 non-null  object
 24  college_conference            6842 non-null   object
 25  jersey_number                 24246 non-null  object
 26  rookie_season                 25037 non-null  int32
 27  last_season                   25037 non-null  int32
 28  latest_team                   25037 non-null  object
 29  status                        25037 non-null  object
 30  ngs_status                    8492 non-null   object
 31  ngs_status_short_description  6870 non-null   object
 32  years_of_experience           25037 non-null  int32
 33  pff_position                  7424 non-null   object
 34  pff_status                    3857 non-null   object
 35  draft_year                    12229 non-null  float64
 36  draft_round                   12229 non-null  float64
 37  draft_pick                    12229 non-null  float64
 38  draft_team                    12229 non-null  object
dtypes: float64(5), int32(3), object(31)
memory usage: 7.2+ MB

,gsis_id,display_name,common_first_name,first_name,last_name,short_name,football_name,suffix,esb_id,nfl_id,pfr_id,pff_id,otc_id,espn_id,smart_id,birth_date,position_group,position,ngs_position_group,ngs_position,height,weight,headshot,college_name,college_conference,jersey_number,rookie_season,last_season,latest_team,status,ngs_status,ngs_status_short_description,years_of_experience,pff_position,pff_status,draft_year,draft_round,draft_pick,draft_team
0,00-0028830,Isaako Aaitui,Isaako,Isaako,Aaitui,None,None,None,AAI622937,None,AaitIs00,6998,2535,14856,32004141-4962-2937-61ff-017b1804dec6,1987-01-25,DL,NT,None,None,76.0,307.0,https://static.www.nfl.com/image/private/f_aut...,UNLV,None,0,2011,2014,WAS,DEV,None,None,2,DI,None,NaN,NaN,NaN,None
1,00-0038389,Israel Abanikanda,Israel,Israel,Abanikanda,I.Abanikanda,Israel,None,ABA159567,56008,AbanIs00,122999,10967,4429202,32004142-4115-9567-2e24-0eab29f6a4b9,2002-10-05,RB,RB,None,None,70.0,225.0,https://static.www.nfl.com/image/upload/f_auto...,Pittsburgh,Atlantic Coast Conference,30,2023,2026,DAL,ACT,ACT,Active,3,HB,A,2023.0,5.0,143.0,NYJ
2,00-0024644,Jon Abbate,Jon,Jon,Abbate,None,None,None,ABB051371,None,None,None,None,None,32004142-4205-1371-db95-1abc96313b69,1985-06-18,LB,LB,None,None,71.0,245.0,https://static.www.nfl.com/image/private/f_aut...,Wake Forest,None,67,2007,2007,HOU,RES,None,None,0,None,None,NaN,NaN,NaN,None
3,ABB498348,Vince Abbott,Vince,Vincent,Abbott,None,None,None,ABB498348,None,abbotvin01,None,None,None,32004142-4249-8348-e00f-5fbbe6a0c73c,1958-05-31,SPEC,K,None,None,71.0,207.0,https://static.www.nfl.com/image/private/f_aut...,California State-Fullerton; Washington,None,0,1987,1988,LAC,ACT,None,None,2,None,None,NaN,NaN,NaN,None
4,00-0031021,Jared Abbrederis,Jared,Jared,Abbrederis,J.Abbrederis,Jared,None,ABB650964,41405,AbbrJa00,8811,3115,16836,32004142-4265-0964-fc36-bb0ad76ff6e6,1990-12-17,WR,WR,WR,WR,73.0,195.0,https://static.www.nfl.com/image/private/f_aut...,Wisconsin,None,10,2014,2017,DET,CUT,CUT,None,4,WR,None,2014.0,5.0,176.0,GB
5,00-0032860,Mehdi Abdesmad,Mehdi,Mehdi,Abdesmad,M.Abdesmad,Mehdi,None,ABD171953,43927,AbdeMe00,11322,5370,2576467,32004142-4417-1953-b577-2572c35b54c1,1991-09-28,DL,DE,DL,INTERIOR_LINE,78.0,284.0,https://static.www.nfl.com/image/private/f_aut...,Boston College,None,68,2016,2016,TEN,RES,CUT,None,0,DI,None,NaN,NaN,NaN,None
6,00-0028564,Isa Abdul-Quddus,Isa,Isa,Abdul-Quddus,None,Isa,None,ABD688172,38044,AbduIs00,6722,1495,14466,32004142-4468-8172-c46a-6ab92c1db0ec,1989-08-03,DB,S,None,None,73.0,196.0,https://static.www.nfl.com/image/private/f_aut...,Fordham,Patriot League,24,2011,2016,MIA,RES,ACT,Active,6,S,None,NaN,NaN,NaN,None
7,00-0032104,Ameer Abdullah,Ameer,Ameer,Abdullah,A.Abdullah,Ameer,None,ABD647726,42397,AbduAm00,9487,3902,2576336,32004142-4464-7726-b649-e09413abd27c,1993-06-13,RB,RB,None,None,69.0,203.0,https://static.www.nfl.com/image/upload/f_auto...,Nebraska,Big Ten Conference,43,2015,2026,JAX,ACT,ACT,Active,12,HB,A,2015.0,2.0,54.0,DET
8,00-0023663,Hamza Abdullah,Hamza,Hamza,Abdullah,None,None,None,ABD655601,30059,AbduHa20,2448,6814,8645,32004142-4465-5601-b9f3-0ea6cfefd92f,1983-08-20,DB,DB,None,None,74.0,216.0,https://static.www.nfl.com/image/private/f_aut...,Washington State,None,23,2005,2011,ARI,ACT,None,None,7,S,None,2005.0,7.0,231.0,TB
9,00-0025940,Husain Abdullah,Husain,Husain,Abdullah,None,Husain,None,ABD660476,33465,AbduHu99,4652,800,11910,32004142-4466-0476-f505-0cb007da0036,1985-07-27,DB,FS,None,None,72.0,204.0,https://static.www.nfl.com/image/private/f_aut...,Washington State,Pacific Ten Conference,39,2008,2015,KC,ACT,ACT,Active,7,S,None,NaN,NaN,NaN,None

In [19]:
test = nfl.import_depth_charts([2024])
print(test.shape)

depth_charts = nfl.import_depth_charts(years)
print(depth_charts.shape)
depth_charts.info()
depth_charts.head(10)

(37312, 15)
(923447, 26)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 923447 entries, 0 to 554214
Data columns (total 26 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   season          369232 non-null  float64
 1   club_code       369232 non-null  object
 2   week            366834 non-null  float64
 3   game_type       369232 non-null  object
 4   depth_team      369232 non-null  object
 5   last_name       369232 non-null  object
 6   first_name      369232 non-null  object
 7   football_name   369232 non-null  object
 8   formation       369232 non-null  object
 9   gsis_id         917870 non-null  object
 10  jersey_number   369232 non-null  object
 11  position        369232 non-null  object
 12  elias_id        369176 non-null  object
 13  depth_position  369232 non-null  object
 14  full_name       369232 non-null  object
 15  dt              554215 non-null  object
 16  team            554215 non-null  object
 17  player_name     553770 non-null  object
 18  espn_id         554215 non-null  object
 19  pos_grp_id      554215 non-null  object
 20  pos_grp         554215 non-null  object
 21  pos_id          554215 non-null  object
 22  pos_name        554215 non-null  object
 23  pos_abb         554215 non-null  object
 24  pos_slot        554215 non-null  float64
 25  pos_rank        554215 non-null  float64
dtypes: float64(4), object(22)
memory usage: 190.2+ MB

,season,club_code,week,game_type,depth_team,last_name,first_name,football_name,formation,gsis_id,jersey_number,position,elias_id,depth_position,full_name,dt,team,player_name,espn_id,pos_grp_id,pos_grp,pos_id,pos_name,pos_abb,pos_slot,pos_rank
0,2015.0,ATL,2.0,REG,2,Freeman,Devonta,Devonta,Offense,00-0031285,33,RB,FRE174508,RB,Devonta Freeman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015.0,ATL,2.0,REG,1,DiMarco,Patrick,Patrick,Offense,00-0028581,42,FB,DIM110572,FB,Patrick DiMarco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015.0,ATL,2.0,REG,3,Williams,Nick,Nick,Offense,00-0029848,1,WR,WIL456782,WR,Nick Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015.0,ATL,2.0,REG,3,Ward,Terron,Terron,Offense,00-0031682,28,RB,WAR275043,RB,Terron Ward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015.0,ATL,2.0,REG,1,Hageman,Ra'Shede,Ra'Shede,Defense,00-0031281,90,DT,HAG152196,DT,Ra'Shede Hageman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015.0,ATL,2.0,REG,1,Soliai,Paul,Paul,Defense,00-0025495,90,DT,SOL128376,NT,Paul Soliai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015.0,ATL,2.0,REG,1,Schofield,O'Brien,O'Brien,Defense,00-0027730,54,LB,SCH441573,LB,O'Brien Schofield,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015.0,ATL,2.0,REG,1,Alford,Robert,Robert,Defense,00-0030528,23,CB,ALF657259,CB,Robert Alford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015.0,ATL,2.0,REG,1,Trufant,Desmond,Desmond,Defense,00-0030562,10,CB,TRU381665,CB,Desmond Trufant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015.0,ATL,2.0,REG,1,Allen,Ricardo,Ricardo,Defense,00-0031181,37,SS,ALL641418,S,Ricardo Allen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
injuries = nfl.import_injuries(years_experiment)
print(injuries.shape)
injuries.info()
injuries.head(10)

(54720, 16)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 54720 entries, 0 to 6214
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   season                     54720 non-null  float64
 1   game_type                  54720 non-null  object
 2   team                       54720 non-null  object
 3   week                       54720 non-null  float64
 4   gsis_id                    54720 non-null  object
 5   position                   54720 non-null  object
 6   full_name                  54720 non-null  object
 7   first_name                 54720 non-null  object
 8   last_name                  54720 non-null  object
 9   report_primary_injury      29098 non-null  object
 10  report_secondary_injury    1906 non-null   object
 11  report_status              29104 non-null  object
 12  practice_primary_injury    54500 non-null  object
 13  practice_secondary_injury  3544 non-null   object
 14  practice_status            54720 non-null  object
 15  date_modified              54720 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(2), object(13)
memory usage: 7.1+ MB

,season,game_type,team,week,gsis_id,position,full_name,first_name,last_name,report_primary_injury,report_secondary_injury,report_status,practice_primary_injury,practice_secondary_injury,practice_status,date_modified
0,2015.0,REG,ARI,1.0,00-0029740,TE,Ifeanyi Momah,Ifeanyi,Momah,None,None,None,Knee,None,Did Not Participate In Practice,2015-09-09 14:14:17+00:00
1,2015.0,REG,ARI,1.0,00-0027869,G,Mike Iupati,Mike,Iupati,Knee,None,Out,Knee,None,Did Not Participate In Practice,2015-09-11 13:06:02+00:00
2,2015.0,REG,ARI,1.0,00-0029638,WR,Michael Floyd,Michael,Floyd,Hand,None,Questionable,Hand,None,Limited Participation in Practice,2015-09-11 13:05:52+00:00
3,2015.0,REG,ARI,1.0,00-0027873,TE,Jermaine Gresham,Jermaine,Gresham,Hamstring,None,Questionable,Hamstring,None,Limited Participation in Practice,2015-09-11 13:05:57+00:00
4,2015.0,REG,ARI,1.0,00-0031044,TE,Troy Niklas,Troy,Niklas,Hamstring,None,Questionable,Hamstring,None,Limited Participation in Practice,2015-09-11 13:06:07+00:00
5,2015.0,REG,ATL,1.0,00-0024272,WR,Devin Hester,Devin,Hester,Toe,None,Out,Toe,None,Did Not Participate In Practice,2015-09-12 11:20:43+00:00
6,2015.0,REG,ATL,1.0,00-0027980,LB,Brooks Reed,Brooks,Reed,Groin,None,Out,Groin,None,Did Not Participate In Practice,2015-09-12 11:20:37+00:00
7,2015.0,REG,ATL,1.0,00-0029770,LB,Joplo Bartu,Joplo,Bartu,Quadricep,None,Probable,Quadricep,None,Full Participation in Practice,2015-09-12 11:20:26+00:00
8,2015.0,REG,ATL,1.0,00-0031285,RB,Devonta Freeman,Devonta,Freeman,Hamstring,None,Probable,Hamstring,None,Full Participation in Practice,2015-09-12 11:20:26+00:00
9,2015.0,REG,ATL,1.0,00-0031279,T,Jake Matthews,Jake,Matthews,Back,None,Probable,Back,None,Full Participation in Practice,2015-09-12 11:20:26+00:00

In [21]:

#Trying to understand why depth charts has so many nulls that dont add up

for year in [2015, 2018, 2021, 2024, 2025, 2026]:
    test = nfl.import_depth_charts([year])
    print(year, test.shape)
    print(test.columns[test.notna().any()].tolist())
    print('---')

2015 (37058, 15)
['season', 'club_code', 'week', 'game_type', 'depth_team', 'last_name', 'first_name', 'football_name', 'formation', 'gsis_id', 'jersey_number', 'position', 'elias_id', 'depth_position', 'full_name']
---
2018 (36560, 15)
['season', 'club_code', 'week', 'game_type', 'depth_team', 'last_name', 'first_name', 'football_name', 'formation', 'gsis_id', 'jersey_number', 'position', 'elias_id', 'depth_position', 'full_name']
---
2021 (37487, 15)
['season', 'club_code', 'week', 'game_type', 'depth_team', 'last_name', 'first_name', 'football_name', 'formation', 'gsis_id', 'jersey_number', 'position', 'elias_id', 'depth_position', 'full_name']
---
2024 (37312, 15)
['season', 'club_code', 'week', 'game_type', 'depth_team', 'last_name', 'first_name', 'football_name', 'formation', 'gsis_id', 'jersey_number', 'position', 'elias_id', 'depth_position', 'full_name']
---
2025 (554215, 12)
['dt', 'team', 'player_name', 'espn_id', 'gsis_id', 'pos_grp_id', 'pos_grp', 'pos_id', 'pos_name', 'pos_abb', 'pos_slot', 'pos_rank']
---
2026 (426595, 12)
['dt', 'team', 'player_name', 'espn_id', 'gsis_id', 'pos_grp_id', 'pos_grp', 'pos_id', 'pos_name', 'pos_abb', 'pos_slot', 'pos_rank']
---

In [22]:
weekly_ids = set(weekly['player_id'].unique())
player_ids = set(players['gsis_id'].unique())

overlap = weekly_ids & player_ids
print(f"Unique IDs in weekly: {len(weekly_ids)}")
print(f"Unique IDs in players: {len(player_ids)}")
print(f"Overlapping IDs: {len(overlap)}")

Unique IDs in weekly: 1978
Unique IDs in players: 25037
Overlapping IDs: 1978